import locationLogoImported from "../images/location-logo.png";
import clockLogoImported from "../images/clock-logo.png";
import { displayReservation } from "./website.js";
let createHome = () => {
  let home = document.createElement("div");
  home.classList.add("home");
  let homeTitle = document.createElement("h1");
  homeTitle.textContent = "Venez découvrir nos fameuses pizzas !";
  home.appendChild(homeTitle);
  let homeSecondTitle = document.createElement("h2");
  homeSecondTitle.textContent = "Faites Maison et avec Amour !";
  home.appendChild(homeSecondTitle);
  let homeButton = document.createElement("button");
  homeButton.textContent = "Réserver";
  home.appendChild(homeButton);
  homeButton.addEventListener("click", () => {
    displayReservation();
  });
  let aboutContainer = document.createElement("div");
  aboutContainer.classList.add("aboutContainer");
  home.appendChild(aboutContainer);
  let addressContainer = document.createElement("div");
  addressContainer.classList.add("addressContainer");
  aboutContainer.appendChild(addressContainer);
  let locationLogo = new Image();
  locationLogo.src = locationLogoImported;
  addressContainer.appendChild(locationLogo);
  let locationText = document.createElement("p");
  locationText.textContent = "1 Rue de la Paix, Paris 2e";
  addressContainer.appendChild(locationText);
  let clockContainer = document.createElement("div");
  clockContainer.classList.add("clockContainer");
  aboutContainer.appendChild(clockContainer);
  let clockLogo = new Image();
  clockLogo.src = clockLogoImported;
  clockContainer.appendChild(clockLogo);
  let clockText = document.createElement("p");
  clockText.textContent = "Lundi - Dimanche : 10h-23h";
  clockContainer.appendChild(clockText);
  return home;
};
export default createHome;
